#!/bin/bash
# get the variable asked for
if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    echo "Usage: copy [variable]"
    echo "Other options:" [variable] | copy
    echo "Copy the variable to the clipboard"
    exit 1
elif [ "$1" ]; then
    COPY_VAR=$1
else
    COPY_VAR=$(cat)
fi

# copy the variable to the clipboard
if [ "$(command -v wl-copy)" ]; then
    wl-copy "$(echo "$COPY_VAR")"
elif [ "$(command -v xclip)" ]; then
    echo "$COPY_VAR" | xclip -selection clipboard
elif [ "$(command -v clip.exe)" ]; then
    echo "$COPY_VAR" | clip.exe
else
    echo "No copy software found on this machine"
    exit 1
fi
