#!/bin/bash

TARGZ_NAME=.docker_images.tar.gz

# ensure the tar.gz file exists before proceeding
if [ ! -f $TARGZ ]; then
    echo "Docker image backup file not found! ($TARGZ)"
    exit 1
fi

# stop all instances and remove all images
docker stop $(docker ps -aq)
docker system prune -af
docker image rm $(docker image ls -aq)

# querry images from tar.gz file
if [ -f /tmp/$TARGZ_NAME ]; then
    docker load -i /tmp/$TARGZ_NAME
fi
if [ -f ~/$TARGZ_NAME ]; then
    docker load -i ~/$TARGZ_NAME
fi
if [ -f $TARGZ_NAME ]; then
    docker load -i $TARGZ_NAME
fi

