console_title_template = "{{.UserName}}@{{.HostName}} : {{.Folder}}"
final_space = true
version = 2

[[blocks]]
alignment = "left"
newline = true
type = "prompt"

	[[blocks.segments]]
	background = "p:bg_white"
	background_templates = [ "{{ if eq .Code 0 }}p:bg_white{{ else }}p:bg_red{{ end }}" ]
	foreground = "p:blue"
	foreground_templates = [ "{{ if eq .Code 0 }}p:blue{{ else }}p:dark_red{{ end }}" ]
	leading_diamond = ""
	style = "diamond"
	template = "{{ if eq .Code 0 }}{{.Icon}}{{ else }}{{ .Code }}{{ end }} "
	type = "os"

		[blocks.segments.properties]
		arch = ""
		debian = ""
		fedora = ""
		linux = ""
		macos = ""
		manjaro = ""
		opensuse = ""
		ubuntu = ""
		windows = ""

	[[blocks.segments]]
	background = "p:bg_white"
	foreground = "p:blue"
	powerline_symbol = ""
	style = "powerline"
	template = "{{ .UserName }}<p:black>@</><p:red>{{ .HostName }}</> "
	type = "session"

		[blocks.segments.properties]
		display_host = true

	[[blocks.segments]]
	background = "p:red"
	foreground = "p:white"
	powerline_symbol = ""
	style = "powerline"
	template = " ⠀"
	type = "root"

	[[blocks.segments]]
	background = "p:bg_blue"
	foreground = "p:white"
	powerline_symbol = ""
	style = "powerline"
	template = "  {{ .Path }} "
	type = "path"

		[blocks.segments.properties]
		folder_separator_icon = "/"
		home_icon = "~"
		max_depth = 2
		style = "letter"

	[[blocks.segments]]
	background = "p:bg_yellow"
	background_templates = [
		"{{ if or (.Working.Changed) (.Staging.Changed) }}p:bg_orange{{ end }}",
		"{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:bg_turquoise{{ end }}",
		"{{ if gt .Ahead 0 }}p:bg_turquoise{{ end }}",
		"{{ if gt .Behind 0 }}p:bg_turquoise{{ end }}"
	]
	foreground = "p:black"
	powerline_symbol = ""
	style = "powerline"
	template = " {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }}{{ if gt .Behind 0 }}⇣{{ end }}{{ if gt .Ahead 0 }}⇡{{ end }} "
	type = "git"

		[blocks.segments.properties]
		fetch_stash_count = true
		fetch_status = true
		fetch_upstream_icon = true

[[blocks]]
alignment = "right"
type = "rprompt"
overflow = "hidden"

	[[blocks.segments]]
	type = "executiontime"
	style = "plain"
	foreground = "p:yellow"
	template = " {{ .FormattedMs }} "

		[blocks.segments.properties]
		threshold = 5000

[palette]
black        = "#000000"
blue         = "#0077c2"
dark_red     = "#632020"
red          = "#e06c75"
yellow       = "#fffb38"
white        = "#ffffff"

bg_blue      = "#0077c2"
bg_orange    = "#ff9248"
bg_red       = "#cc2222"
bg_turquoise = "#30d5c8"
bg_white     = "#fbfbfb"
bg_yellow    = "#fffb38"

